Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Write-Step {
  param([string]$Message)
  Write-Host "[setup] $Message"
}

function Find-CommandPath {
  param(
    [string[]]$Candidates
  )

  foreach ($candidate in $Candidates) {
    if ([string]::IsNullOrWhiteSpace($candidate)) {
      continue
    }

    if (Test-Path -LiteralPath $candidate) {
      return (Resolve-Path -LiteralPath $candidate).Path
    }

    $command = Get-Command $candidate -ErrorAction SilentlyContinue
    if ($command) {
      return $command.Source
    }
  }

  return $null
}

function Set-EnvValue {
  param(
    [hashtable]$Map,
    [string]$Key,
    [string]$Value
  )

  if ([string]::IsNullOrWhiteSpace($Value)) {
    return
  }

  $Map[$Key] = $Value
}

function Get-EnvValueOrDefault {
  param(
    [hashtable]$Map,
    [string]$Key,
    [string]$DefaultValue
  )

  if ($Map.ContainsKey($Key) -and -not [string]::IsNullOrWhiteSpace($Map[$Key])) {
    return $Map[$Key]
  }

  return $DefaultValue
}

function Read-EnvFile {
  param([string]$Path)

  $map = [ordered]@{}

  if (-not (Test-Path -LiteralPath $Path)) {
    return $map
  }

  foreach ($line in Get-Content -LiteralPath $Path) {
    if ($line -match '^\s*#' -or $line -notmatch '=') {
      continue
    }

    $name, $value = $line -split '=', 2
    $map[$name.Trim()] = $value.Trim()
  }

  return $map
}

$repoRoot = Split-Path -Parent $PSScriptRoot
Set-Location -LiteralPath $repoRoot

Write-Step "Repository root: $repoRoot"

$envPath = Join-Path $repoRoot '.env'
$existingEnv = Read-EnvFile $envPath

$nodePath = Find-CommandPath @('node')
$npmPath = Find-CommandPath @('npm', 'npm.cmd')
$ffmpegPath = Find-CommandPath @(
  $env:FFMPEG_PATH,
  $existingEnv['FFMPEG_PATH'],
  'C:\ffmpeg\bin\ffmpeg.exe',
  'ffmpeg'
)
$ffprobePath = Find-CommandPath @(
  $env:FFPROBE_PATH,
  $existingEnv['FFPROBE_PATH'],
  'C:\ffmpeg\bin\ffprobe.exe',
  'ffprobe'
)
$whisperPath = Find-CommandPath @(
  $env:WHISPER_COMMAND_PATH,
  $existingEnv['WHISPER_COMMAND_PATH'],
  (Join-Path $env:LOCALAPPDATA 'Python\pythoncore-3.14-64\Scripts\whisper.exe'),
  'whisper'
)

if (-not $nodePath) {
  throw "Node.js 20+ is required but was not found on PATH. Install Node.js, reopen PowerShell, then run .\setup.cmd again."
}

if (-not $npmPath) {
  throw "npm was not found. Install a standard Node.js distribution, reopen PowerShell, then run .\setup.cmd again."
}

if (-not $ffmpegPath) {
  throw "ffmpeg was not found. Install ffmpeg or set FFMPEG_PATH before running setup."
}

if (-not $ffprobePath) {
  throw "ffprobe was not found. Install ffprobe or set FFPROBE_PATH before running setup."
}

if (-not $whisperPath) {
  throw "Whisper CLI was not found. Install Python Whisper or set WHISPER_COMMAND_PATH before running setup."
}

$envMap = [ordered]@{}

if (Test-Path -LiteralPath $envPath) {
  Write-Step "Updating existing .env"
  foreach ($line in Get-Content -LiteralPath $envPath) {
    if ($line -match '^\s*#' -or $line -notmatch '=') {
      continue
    }

    $name, $value = $line -split '=', 2
    $envMap[$name.Trim()] = $value.Trim()
  }
} else {
  Write-Step "Creating .env"
}

Set-EnvValue $envMap 'FFMPEG_PATH' $ffmpegPath
Set-EnvValue $envMap 'FFPROBE_PATH' $ffprobePath
Set-EnvValue $envMap 'WHISPER_COMMAND_PATH' $whisperPath
Set-EnvValue $envMap 'WEB_UI_HOST' (Get-EnvValueOrDefault $envMap 'WEB_UI_HOST' '127.0.0.1')
Set-EnvValue $envMap 'WEB_UI_PORT' (Get-EnvValueOrDefault $envMap 'WEB_UI_PORT' '3000')
Set-EnvValue $envMap 'WEB_UI_WORKSPACE_ROOT' (Get-EnvValueOrDefault $envMap 'WEB_UI_WORKSPACE_ROOT' '.tmp-web-ui')

$envLines = @(
  "# Generated by scripts/setup.ps1",
  "FFMPEG_PATH=$($envMap['FFMPEG_PATH'])",
  "FFPROBE_PATH=$($envMap['FFPROBE_PATH'])",
  "WHISPER_COMMAND_PATH=$($envMap['WHISPER_COMMAND_PATH'])",
  "WEB_UI_HOST=$($envMap['WEB_UI_HOST'])",
  "WEB_UI_PORT=$($envMap['WEB_UI_PORT'])",
  "WEB_UI_WORKSPACE_ROOT=$($envMap['WEB_UI_WORKSPACE_ROOT'])"
)

Set-Content -LiteralPath $envPath -Value $envLines -Encoding UTF8
Write-Step "Wrote .env"

Write-Step "Installing npm dependencies"
& $npmPath install
if ($LASTEXITCODE -ne 0) {
  throw "npm install failed."
}

Write-Step "Setup complete"
Write-Host ""
Write-Host "Detected tools:"
Write-Host "  node:    $nodePath"
Write-Host "  npm:     $npmPath"
Write-Host "  ffmpeg:  $ffmpegPath"
Write-Host "  ffprobe: $ffprobePath"
Write-Host "  whisper: $whisperPath"
Write-Host ""
Write-Host "Next commands:"
Write-Host "  npm run web-ui"
Write-Host "  npm run generate-subtitles -- --help"
